### ISSUE TITLE
Add Harrington Healthcare

### ISSUE THREAD

**Issue by harcod** [livgust/covid-vaccine-scrapers#165]
https://app.acuityscheduling.com/schedule.php?owner=22192301&calendarID=5202038

**Comment by pfurbacher** [comment]
I might be wrong, but from what I can tell, Harrington has switched scheduling from signup.com to Acuity Scheduling. If this is correct, the current Harrington scraper, based on signup.com and Google forms, is out-dated. 

The URL above is for the non-restricted registration. The URL for the town restricted registration is: 

https://app.acuityscheduling.com/schedule.php?owner=22192301&calendarID=5202050

I was lucky to grab the relevant HTML for two slots on different days, one of which disappeared within minutes, and in the time taken to write this up, the second one has disappeared.

Since it's an Acuity Scheduling app, there's a good bit of similarity to Trinity EMS. Even though it doesn't use the same calendar style and CSS class to indicate a day with slots, it does use the same "next month" paging mechanism.

Here are the two HTML snippets which contain info on slots: 

```
<input type="radio" 
    class="time-selection" 
    name="time[]" 
    data-qa="select-day-29-slot-0" 
    data-readable-date="2021-03-29" 
    value="2021-03-29 11:45" 
    id="appt1617032700" 
    aria-labelledby="lbl_appt1617032700">
    
<input type="radio" 
    class="time-selection" 
    name="time[]" 
    data-qa="select-day-07-slot-0" 
    data-readable-date="2021-04-07" 
    value="2021-04-07 10:00" 
    id="appt1617804000" 
    aria-labelledby="lbl_appt1617804000">
```

**Comment by livgust** [comment]
You're brilliant! In the meantime I'm going to delete the existing harrington scraper, or at least ensure it doesn't run

**Comment by livgust** [comment]
#180 closes this
