### ISSUE TITLE
add CVS

### ISSUE THREAD

**Issue by carloshgaray** [livgust/covid-vaccine-scrapers#3]
we want to add CVS to list of scraped availability

**Comment by carloshgaray** [comment]
General procedure will be:

1. Add list of all zip codes in MA to raw json and/or http request
2. For each zip code, enumerate all CVS locations to create database of all stores, their addresses, contact info, etc.
3. For each zip code, enumerate all available vaccine slots for the next 30 days
4. Serialize results in expected output JSON output format

**Comment by johnhawkinson** [comment]
Re 1, why not just use https://www.cvs.com/immunizations/covid-19-vaccine.vaccine-status.ma.json which does `getInventorybyCity`?

Hrm…ok, answer: Because it doesn't give you zipcodes and city names are insufficient, e.g. Cambridge's site only shows up in CVS's search under "Alewife, MA" even though their address has it in Cambridge (where it indeed is).
