### ISSUE TITLE
Add Pediatric Associates of Greater Salem

### ISSUE THREAD

**Issue by livgust** [livgust/covid-vaccine-scrapers#7]
Notes from spreadsheet:
EASY. Uses athenahealth. There's a request https://framework-backend.scheduling.athena.io/v1/graphql with post data "operationName: "SearchAvailabilityDates"" that gives us all the data we need; if we'd prefer to have an api hook into that, I can probably ask for it from coworkers. - Olivia

**Comment by dragthemagicpuffin** [comment]
Olivia, can you assign this to me?
I don't have knowledge of the athena scheduling graphql backend, but this does seem like an easy one to start with.

**Comment by dragthemagicpuffin** [comment]
Their website (pags.com) says "PAGS does not yet have the ability to provide COIVID vaccines for our patients. Please do not call our office to ask about scheduling a COVID vaccine"
So... I doubt this is the highest priority site to scrape.

But... Olivia, where are you getting the info about the athena.io POST request? I am unsure how to retrace your steps.

**Comment by livgust** [comment]
Hi!!! You got it! The sign-up page is linked on vaxfinder.mass.gov. The data all used to be in a spreadsheet that was periodically updated and available on the state website but they stopped publishing it once vaxfinder went live.
Here's the site: https://consumer.scheduling.athena.io/?departmentId=2804-102

When I logged on the day I reported this issue, I didn't get the "there are no appointments for 3 months" message. I was just browsing through the requests on the Network tab and saw there was one (which I linked above) that showed me all the availability data.

**Comment by dragthemagicpuffin** [comment]
That page (consumer.scheduling.athena.io) does not POST a SearchAvailabilityDates operation when I visit but rather a GetFilters operation. That graphql response is 
{"data":{"getFilters":null}}

Difficulties:
- I don't have an example of SearchAvailabilityDates, and not sure how to make one successfully. (I get a 400 bad request...)
(Does this operation come after a GetFilters? before? or instead of?)
- I'm not sure what the GetFilters response would be if there were availability, or if it would be any different.

**Comment by dragthemagicpuffin** [comment]
I'd like to push what I have and move on. @livgust  I think I need access to the repo (push gets me a 403 error).

**Comment by livgust** [comment]
Sure! Sorry for the delay. Adding you now.
