### ISSUE TITLE
Add UMass Memorial Marlborough Hospital

### ISSUE THREAD

**Issue by livgust** [livgust/covid-vaccine-scrapers#9]
Another easy MyChart one

**Comment by benpatterson** [comment]
I'll plan on tackling this later today unless someone beats me to it (which, like, is totally cool if ya do!)

**Comment by livgust** [comment]
Hey @benpatterson, FYI @tkjones117 is working on another MyChart one so you might want to check in with her to see if you are duplicating efforts! I'm not sure how much code will be reusable between the different Epic/MyChart websites but I imagine there will be some overlap.

Thanks!

**Comment by tkjones117** [comment]
@benpatterson I've posted updates here: https://github.com/livgust/covid-vaccine-scrapers/issues/5

**Comment by benpatterson** [comment]
Calling out I've been working on getting my dev environment set up, but am not done, yet. I will spare folks the grief, but minimal progress, I'm afraid. I hope to get back to it tonight or tomorrow.

**Comment by tkjones117** [comment]
All good @benpatterson! Feel free to post questions in Slack too, I’m sure if you’re running into env setup issues then others are too.

**Comment by benpatterson** [comment]
Thanks @tkjones117! I've sorted it out and will ping back when I've got more for folks. ✔️

**Comment by benpatterson** [comment]
Just calling out that I've got some basics in place but not at the point where we have data. Looks like I will need to get the verification token & (guessing) set a cookie in order to make the request. The call to mychart looks like it needs to be a `POST` so likely need to put it together with a `GET` beforehand for setting those up.

Will put in more time tomorrow (which is a day off for me).

**Comment by benpatterson** [comment]
Posting my changes on top of @adpjay 's MyChart/MassMercantile branch.

Mass Memorial Marlborough has not had availability every time I've checked, so I can't say I've verified end-to-end
